### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by felixfbecker** [amenadiel/jpgraph#5]
I haven't tested this, but [this thread](https://groups.google.com/forum/?hl=en-GB#!topic/jpgraph/ZgFLjda26fY) suggests that the original jpGraph is not compatible with PHP7. As this is a "modernized" version of jpGraph, have you tested if it supports PHP7?

I really like your work, I have to use jpGraph and would much rather use true namespaces and composer instead of the vanilla version. Are you actively supporting this? Can I depend on it in production?
EDIT: I meant if you're planning on pulling in new versions as they're released. Seeing that the last one was in 2010 this probably isn't going to be an issue.

**Comment by amenadiel** [comment]
I'm using this component in production and it's working fine as of PHP 5.6. 

I can make it work under PHP7 with little or no effort, but I'd appreciate if other people were involved in the  project vía pull requests.

In particular, this project has a lot of examples that I haven't yet recycled to make proper unit tests, and without them I cannot resort to CI yet.

**Comment by felixfbecker** [comment]
Awesome. Can you point me where I could help out?

**Comment by felixfbecker** [comment]
And I take from your answer that it _currently_ does _not_ support PHP7?

**Comment by amenadiel** [comment]
I'm just not sure, I haven't used it in PHP7. And the codebase is just too broad and coupled to predict such outcome.

If you want to help, install PHP7, clone this repo, run it locally with  the built in server, and go through the examples.

**Comment by felixfbecker** [comment]
I just saw the note about not all examples working. I will try to get as many of them as I can working on PHP 5.6 and then see if I can make them work on PHP 7. There seems to be a PHP version check somewhere in the code as when I first tried with PHP 7 it said "Unsupported PHP version". Imo this should be completely removed because it can be ensured with composer `require` field.
